### ISSUE TITLE
Error with no longer supported

### ISSUE THREAD

**Issue by MrNhanh** [victorharry/zap-gpt#3]
Dear @victorharry 
I get this error, please help me to solve

PS C:\Users\Asus\zap-gpt> npm install
npm WARN deprecated puppeteer@14.4.1: < 19.2.0 is no longer supported
npm ERR! code 1
npm ERR! path C:\Users\Asus\zap-gpt\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r1002410! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! [Error: ENOSPC: no space left on device, write] {
npm ERR!   errno: -4055,
npm ERR!   code: 'ENOSPC',
npm ERR!   syscall: 'write'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus\AppData\Local\npm-cache\_logs\2023-02-15T03_48_06_329Z-debug-0.log

**Comment by victorharry** [comment]
Occasionally, Venom may cause these bugs due to updates in its sub-dependencies. As a solution, I plan to switch from using Venom-Bot to WhatsApp-Web.js. I sincerely apologize for the delay in responding!
