### ISSUE TITLE
OpenAI Response Error

### ISSUE THREAD

**Issue by badnewsdev** [victorharry/zap-gpt#5]
Olá, tudo bem?

Ao executar o bot, recebo a seguinte mensagem.

❌ OpenAI Response Error

Porém, meu arquivo env está certo, poderia me ajudar?

OPENAI_KEY=MINHAKEY
ORGANIZATION_ID=MY ORG ID
PHONE_NUMBER=55myfon

**Comment by badnewsdev** [comment]
Chegou a funcionar uma vez no privado, quando mandei mensagem de novo, apareceu o mesmo erro.
No console aparece que o tempo foi excedido.

O que posso fazer?
![image](https://user-images.githubusercontent.com/104029442/225395630-3e8b5648-7802-49ab-b562-0299c566b084.png)
![image](https://user-images.githubusercontent.com/104029442/225395699-a375f6a6-ac55-4df1-8e79-f9c8e925665e.png)

**Comment by Wellington-Lucas** [comment]
![Sem título](https://user-images.githubusercontent.com/109008241/226142620-38c2255e-1df7-463c-98c2-d889306bedb7.png)
O meu tbm está dando ❌ OpenAI Response Error, porém no cmd aparece esse erro.

**Comment by victorharry** [comment]
Galera façam um pull novamente no projeto, alguns valores da requisição foram atualizados e vão resolver esse problema!
